apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mongodb-vpa
  namespace: chat-app
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: mongodb-statefulset
  updatePolicy:
    updateMode: "Auto"
